spring:
  application:
    name: ocva

  datasource:
    url: jdbc:postgresql://ep-soft-smoke-acmstl8y-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_PLsB6xc1pIml
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true